[project]
name = "applied-programming-2025"
version = "0.1.0"
description = "The exercises for the Applied Programming class of 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.12.4",
]

[dependency-groups]
staff = [
    "nbformat>=5.10.4",
]
